import { createSupabaseServerClient } from '@/lib/db/supabase-server';
import { getActivePersona } from '@/lib/auth/context-service';
import { isQualityEnabled } from '@/lib/quality/tenant-templates';

/**
 * ============================================================================
 * Quality Evidence Service (دليل الجودة) — Phase 3E
 * ============================================================================
 *
 * وحدة **خادمية فقط**. تُنشئ سجل `quality_evidence` **لمؤشر مُسجَّل حقيقي فقط** — بلا تزييف.
 *
 * بنية `quality_evidence` قائمة على المؤشر (indicator-based):
 *   - تتطلّب `indicator_id` (FK إلى `quality_indicators` بـ UNIQUE(school_id, code))،
 *   - و`academic_year_id` (FK NOT NULL) — سنة دراسية نشطة للمدرسة،
 *   - و`value` رقمية، و`source_module` مقيّد بـ CHECK.
 *
 * fail-closed صارم (لا دليل وهمي):
 *   - مؤشر غير مزروع لهذه المدرسة → `indicator_not_seeded`.
 *   - لا سنة دراسية نشطة → `no_active_academic_year`.
 *   - جودة غير مفعّلة للمدرسة (سجلّ المستأجر) → `quality_disabled`.
 *
 * RLS: سياسة `qe_insert` تسمح بالإدراج لـ `quality_coordinator`/`school_admin` فقط عبر العميل
 *   المصادَق؛ الأدلة الآلية من وحدات أخرى (حضور…) تأتي عبر triggers `SECURITY DEFINER` (M78).
 *
 * الحالة الراهنة (PRE-LAUNCH): `quality_indicators` و`academic_years` فارغان (0 صف) — فالخدمة
 *   **خاملة** (تُعيد سبباً واضحاً) حتى يُزرَع المؤشر + السنة. الزرع خطوة DB منفصلة (تتطلب موافقة).
 */

// يطابق قيد CHECK على public.quality_evidence.source_module
export type QualityEvidenceModule =
    | 'attendance'
    | 'lrc'
    | 'health'
    | 'behavior'
    | 'counselor'
    | 'hr'
    | 'activity';

export interface CreateQualityEvidenceInput {
    /** كود مؤشر مُسجَّل في quality_indicators (school_id, code) */
    indicatorCode: string;
    sourceModule: QualityEvidenceModule;
    /** القيمة الرقمية للدليل (من بيانات حقيقية) */
    value: number;
    /** معرّف الحدث المصدر (uuid) — يُستخدم لمنع التكرار */
    sourceEventId?: string;
    /** YYYY-MM-DD — افتراضي CURRENT_DATE في DB */
    evidenceDate?: string;
    notes?: string;
    /** true = أُنشئ آلياً */
    autoGenerated?: boolean;
}

export type CreateQualityEvidenceResult =
    | { ok: true; id: string; deduped: boolean }
    | {
          ok: false;
          reason:
              | 'unauthenticated'
              | 'no_school_context'
              | 'quality_disabled'
              | 'indicator_not_seeded'
              | 'no_active_academic_year'
              | 'db_error';
          message?: string;
      };

export async function createQualityEvidence(
    input: CreateQualityEvidenceInput,
): Promise<CreateQualityEvidenceResult> {
    const persona = await getActivePersona();
    if (!persona) return { ok: false, reason: 'unauthenticated' };
    if (!persona.schoolId) return { ok: false, reason: 'no_school_context' };
    const schoolId = persona.schoolId;

    // المدرسة يجب أن تكون مُفعّلة الجودة في سجلّ المستأجر (fail-closed للمجهول)
    if (!isQualityEnabled(schoolId)) return { ok: false, reason: 'quality_disabled' };

    const supabase = await createSupabaseServerClient();

    // المؤشر يجب أن يكون مزروعاً ونشطاً لهذه المدرسة — وإلا لا دليل (لا تزييف)
    const { data: indicator } = await supabase
        .from('quality_indicators')
        .select('id')
        .eq('school_id', schoolId)
        .eq('code', input.indicatorCode)
        .eq('is_active', true)
        .limit(1)
        .maybeSingle();
    if (!indicator?.id) return { ok: false, reason: 'indicator_not_seeded' };

    // سنة دراسية نشطة للمدرسة
    const { data: year } = await supabase
        .from('academic_years')
        .select('id')
        .eq('school_id', schoolId)
        .eq('is_active', true)
        .limit(1)
        .maybeSingle();
    if (!year?.id) return { ok: false, reason: 'no_active_academic_year' };

    // منع التكرار عبر source_event_id (يوافق partial UNIQUE index في M78)
    if (input.sourceEventId) {
        const { data: dup } = await supabase
            .from('quality_evidence')
            .select('id')
            .eq('source_event_id', input.sourceEventId)
            .limit(1)
            .maybeSingle();
        if (dup?.id) return { ok: true, id: dup.id as string, deduped: true };
    }

    // persona للتسجيل (recorded_by) — اختياري
    const { data: personaRow } = await supabase
        .from('user_personas')
        .select('id')
        .eq('user_id', persona.userId)
        .eq('school_id', schoolId)
        .eq('role', persona.role)
        .limit(1)
        .maybeSingle();

    const row: Record<string, unknown> = {
        school_id: schoolId,
        indicator_id: indicator.id,
        source_event_id: input.sourceEventId ?? null,
        source_module: input.sourceModule,
        value: input.value,
        notes: input.notes ?? null,
        auto_generated: input.autoGenerated ?? false,
        academic_year_id: year.id,
        recorded_by_persona_id: personaRow?.id ?? null,
    };
    if (input.evidenceDate) row.evidence_date = input.evidenceDate;

    const { data, error } = await supabase
        .from('quality_evidence')
        .insert(row)
        .select('id')
        .single();

    if (error || !data) {
        return { ok: false, reason: 'db_error', message: error?.message };
    }
    return { ok: true, id: data.id as string, deduped: false };
}
